gui:
  nerdFontsVersion: "3"
  showFileIcons: true
  mouseEvents: true
  scrollPastBottom: true
  scrollOffMargin: 3
  portraitMode: "auto"
  mainPanelSplitMode: "flexible"
  animateExplosion: true
  
  theme:
    activeBorderColor:
      - '#7aa2f7' # Tokyo Night blue
      - bold
    inactiveBorderColor:
      - '#565f89' # Tokyo Night dark blue/gray
    optionsTextColor:
      - '#9ece6a' # Tokyo Night green
    selectedLineBgColor:
      - '#292e42' # Tokyo Night selection bg
    cherryPickedCommitBgColor:
      - '#3b4261' # Tokyo Night darker blue
    cherryPickedCommitFgColor:
      - '#7aa2f7' # Tokyo Night blue
    unstagedChangesColor:
      - '#f7768e' # Tokyo Night red
    defaultFgColor:
      - '#c0caf5' # Tokyo Night foreground
    searchingActiveBorderColor:
      - '#ff9e64' # Tokyo Night orange
    markedBaseCommitBgColor:
      - "#bb9af7"  # Purple for marked commits
    markedBaseCommitFgColor:
      - "#1a1b26"  # Dark background
    inactiveViewSelectedLineBgColor:
      - "#292e42"  # Subtle highlight for inactive views
  
  branchColors:
    'feature': '#7aa2f7'    # Blue for feature branches
    'bugfix': '#f7768e'     # Red for bugfix branches
    'release': '#9ece6a'    # Green for release branches
    'hotfix': '#ff9e64'     # Orange for hotfix branches
    'development': '#bb9af7' # Purple for development branch

  showFileTree: true
  showListFooter: true
  showRandomTip: true
  showBottomLine: true
  expandFocusedSidePanel: true
  skipStashWarning: true
  skipDiscardChangeWarning: true

git:
  log:
    showGraph: "always"
    showWholeGraph: true

  paging:
    colorArg: always
    pager: delta --dark --paging=never 

  commit:
    autoWrapCommitMessage: true
    autoWrapWidth: 72

  commitPrefix:
    pattern: "^(feature|bugfix|hotfix)/(\\w+-\\w+).*"
    replace: "[$2] "

  autoFetch: true
  autoRefresh: true
  fetchAll: true
  autoStageResolvedConflicts: true

refresher:
  refreshInterval: 5  # Check for file changes every 5 seconds
  fetchInterval: 60   # Fetch from remote every minute
