gui:
  nerdFontsVersion: "3"
  showFileIcons: true
  mouseEvents: true
  scrollPastBottom: true
  scrollOffMargin: 3
  portraitMode: "auto"
  mainPanelSplitMode: "flexible"
  animateExplosion: true
  
  theme:
    commitauthorcolor:
      - "#00a3a3" 
    activeBorderColor:
      - '#007373' # Accent color
      - bold
    inactiveBorderColor:
      - '#9CA3AF' # Mid-gray for visibility
    optionsTextColor:
      - '#007373' # Accent color
    selectedLineBgColor:
      - '#E5E7EB' # Soft light gray
    cherryPickedCommitBgColor:
      - '#D1D5DB' # Light gray
    cherryPickedCommitFgColor:
      - '#007373' # Accent color
    unstagedChangesColor:
      - '#D97706' # Muted orange
    defaultFgColor:
      - '#14161B' # Dark text color
    searchingActiveBorderColor:
      - '#D97706' # Orange
    markedBaseCommitBgColor:
      - '#007373' # Accent color
    markedBaseCommitFgColor:
      - '#FFFFFF' # Pure white for contrast
    inactiveViewSelectedLineBgColor:
      - '#E5E7EB' # Light gray

  branchColors:
    'feature': '#007373' # Accent color
    'bugfix': '#D97706' # Muted orange
    'release': '#10B981' # Green
    'hotfix': '#EF4444' # Soft red
    'development': '#14161B' # Dark text color

  showFileTree: true
  showListFooter: true
  showRandomTip: true
  showBottomLine: true
  expandFocusedSidePanel: true
  skipStashWarning: true
  skipDiscardChangeWarning: true

git:
  log:
    showGraph: "always"
    showWholeGraph: true

  paging:
    colorArg: always
    pager: delta --light --features=hoopoe --syntax-theme=GitHub --paging=never 

  commit:
    autoWrapCommitMessage: true
    autoWrapWidth: 72

  commitPrefix:
    pattern: "^(feature|bugfix|hotfix)/(\\w+-\\w+).*"
    replace: "[$2] "

  autoFetch: true
  autoRefresh: true
  fetchAll: true
  autoStageResolvedConflicts: true

refresher:
  refreshInterval: 5  # Check for file changes every 5 seconds
  fetchInterval: 60   # Fetch from remote every minute

