gui:
  nerdFontsVersion: "3"
  showFileIcons: true
  mouseEvents: true
  scrollPastBottom: true
  scrollOffMargin: 3
  portraitMode: "auto"
  mainPanelSplitMode: "flexible"
  animateExplosion: true
  
  theme:
    commitauthorcolor:
      - "#00a3a3" 
    activeBorderColor:
      - '#00A3A3' # Brighter version of accent
      - bold
    inactiveBorderColor:
      - '#005F5F' # Darker accent
    optionsTextColor:
      - '#00A3A3' # Brighter version of accent
    selectedLineBgColor:
      - '#1E1F26' # Slightly lighter than text color
    cherryPickedCommitBgColor:
      - '#1B2426' # Similar dark tone
    cherryPickedCommitFgColor:
      - '#00A3A3' # Brighter accent
    unstagedChangesColor:
      - '#F4A261' # Muted orange for contrast
    defaultFgColor:
      - '#DADADA' # Light gray
    searchingActiveBorderColor:
      - '#F4A261' # Orange for focus
    markedBaseCommitBgColor:
      - '#007373' # Accent
    markedBaseCommitFgColor:
      - '#14161B' # Dark text color
    inactiveViewSelectedLineBgColor:
      - '#1B2426' # Dark tone

  branchColors:
    'feature': '#007373' # Accent
    'bugfix': '#F4A261' # Orange
    'release': '#00A3A3' # Brighter accent
    'hotfix': '#F2849E' # Soft red
    'development': '#DADADA' # Light gray

  showFileTree: true
  showListFooter: true
  showRandomTip: true
  showBottomLine: true
  expandFocusedSidePanel: true
  skipStashWarning: true
  skipDiscardChangeWarning: true

git:
  log:
    showGraph: "always"
    showWholeGraph: true

  paging:
    colorArg: always
    pager: delta --dark --paging=never 

  commit:
    autoWrapCommitMessage: true
    autoWrapWidth: 72

  commitPrefix:
    pattern: "^(feature|bugfix|hotfix)/(\\w+-\\w+).*"
    replace: "[$2] "

  autoFetch: true
  autoRefresh: true
  fetchAll: true
  autoStageResolvedConflicts: true

refresher:
  refreshInterval: 5  # Check for file changes every 5 seconds
  fetchInterval: 60   # Fetch from remote every minute

