# the ID or name of the model that is selected by default on launch
default_model = "ollama/mistral"
# the system prompt on launch
system_prompt = """
You are my code assistant. 

Please try be brief on your explanations.

Since I understand better with examples, show me examples 
when you think the output will be too long

When possible output only code.
""""
# change the syntax highlighting theme of code in messages
# choose from https://pygments.org/styles/
# defaults to "monokai"
message_code_theme = "github-dark"

# example of adding local llama3 support
# only the `name` field is required here.
[[models]]
name = "ollama/mistral"

[[models]]
name = "ollama/gemma2:9b"

[[models]]
name = "ollama/codegemma"
