-- local colors = require('lcarv.colors')
-- vim.api.nvim_set_hl(0, "EyelinerPrimary", { fg = "#eb53ed", underline = true })
-- vim.api.nvim_set_hl(0, "EyelinerSecondary", { fg = "#00ffff", bold = true, underline = true })
