#!/bin/sh

# ANSI color scheme script by github.com/joshdk https://github.com/joshdk/hedgehogs
red=$(printf '\e[31m')
grn=$(printf '\e[32m')
ylw=$(printf '\e[33m')
blu=$(printf '\e[34m')
mag=$(printf '\e[35m')
cya=$(printf '\e[36m')

bld=$(printf '\e[1m')
rst=$(printf '\e[0m')

cat << ART
$ylw   ╷╽╽╽╽╽╽╽╽╽╷     $grn   ╷╽╽╽╽╽╽╽╽╽╷     $mag   ╷╽╽╽╽╽╽╽╽╽╷    
$ylw  ╽┃┃┃┃┃┃┃┃┃┃┃╽    $grn  ╽┃┃┃┃┃┃┃┃┃┃┃╽    $mag  ╽┃┃┃┃┃┃┃┃┃┃┃╽   
$ylw ┪┃┃┃┃┃┃┃┃┃┃' .\   $grn ┪┃┃┃┃┃┃┃┃┃┃' .\   $mag ┪┃┃┃┃┃┃┃┃┃┃' .\  
$ylw  ╹┃┃┃┃┃┃┃┃⧓ ___•  $grn  ╹┃┃┃┃┃┃┃┃⧓ ___•  $mag  ╹┃┃┃┃┃┃┃┃⧓ ___• 
ART
